substitutions:
  device_name: p1mini
  device_password: !secret p1mini_password
  device_api_key: !secret p1mini_api_key

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp-${device_name}"
    password: "${device_password}"

captive_portal:

# Enable logging
logger:
  level: INFO              # Set to DEBUG if you are having issues!
  baud_rate: 0             # disable logging over uart

# Enable Home Assistant API
api:
  #password: "${device_password}" ### Deprecated
  encryption:
    key: "${device_api_key}"

ota:
  password: "${device_password}"

web_server:
  port: 80
  ota: false
#  auth:
#    username: admin
#    password: "${device_password}"

external_components:
  - source: components

switch:
  - platform: gpio
    id: p1_rts             # Not needed if the RTS signal is not connected to a GPIO
    pin:
      number: D2
  - platform: gpio
    id: status_led
    pin:
      number: D4
      inverted: true

uart:
  id: my_uart
  tx_pin:
    number: TX
    inverted: true
    mode: OUTPUT_OPEN_DRAIN
  rx_pin:
    number: RX
    inverted: true         # Set to false if inverting in hardware
    mode: INPUT_PULLUP     # Set to INPUT if inverting in hardware
  baud_rate: 115200
  rx_buffer_size: 512      # Probably not needed, but it is good to have some margin.

p1_mini:
  id: p1_mini_1
  uart_id: my_uart
  minimum_period: 2s       # Should be 0 (zero) if the RTS signal is not connected.
  secondary_p1: false
  on_ready_to_receive:
    then:
      - switch.turn_on: p1_rts
      - switch.turn_on: status_led
  on_update_received:
    then:
      - switch.turn_off: p1_rts
      - switch.turn_off: status_led
  on_communication_error:
    then:
      - switch.turn_off: p1_rts
      - switch.turn_off: status_led

sensor:
- platform: wifi_signal
  name: "${device_name} WiFi Signal"
  update_interval: 10s
- platform: p1_mini
  obis_code: "1.8.0"
  name: "Cumulative Active Import"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
- platform: p1_mini
  obis_code: "2.8.0"
  name: "Cumulative Active Export"
  unit_of_measurement: kWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"
- platform: p1_mini
  obis_code: "3.8.0"
  name: "Cumulative Reactive Import"
  unit_of_measurement: kvarh
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "4.8.0"
  name: "Cumulative Reactive Export"
  unit_of_measurement: kvarh
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "1.7.0"
  name: "Momentary Active Import"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "2.7.0"
  name: "Momentary Active Export"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "3.7.0"
  name: "Momentary Reactive Import"
  unit_of_measurement: kvar
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "4.7.0"
  name: "Momentary Reactive Export"
  unit_of_measurement: kvar
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "21.7.0"
  name: "Momentary Active Import Phase 1"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "22.7.0"
  name: "Momentary Active Export Phase 1"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "41.7.0"
  name: "Momentary Active Import Phase 2"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "42.7.0"
  name: "Momentary Active Export Phase 2"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "61.7.0"
  name: "Momentary Active Import Phase 3"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "62.7.0"
  name: "Momentary Active Export Phase 3"
  unit_of_measurement: kW
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "23.7.0"
  name: "Momentary Reactive Import Phase 1"
  unit_of_measurement: kvar
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "24.7.0"
  name: "Momentary Reactive Export Phase 1"
  unit_of_measurement: kvar
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "43.7.0"
  name: "Momentary Reactive Import Phase 2"
  unit_of_measurement: kvar
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "44.7.0"
  name: "Momentary Reactive Export Phase 2"
  unit_of_measurement: kvar
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "63.7.0"
  name: "Momentary Reactive Import Phase 3"
  unit_of_measurement: kvar
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "64.7.0"
  name: "Momentary Reactive Export Phase 3"
  unit_of_measurement: kvar
  accuracy_decimals: 3
- platform: p1_mini
  obis_code: "32.7.0"
  name: "Voltage Phase 1"
  unit_of_measurement: V
  accuracy_decimals: 1
- platform: p1_mini
  obis_code: "52.7.0"
  name: "Voltage Phase 2"
  unit_of_measurement: V
  accuracy_decimals: 1
- platform: p1_mini
  obis_code: "72.7.0"
  name: "Voltage Phase 3"
  unit_of_measurement: V
  accuracy_decimals: 1
- platform: p1_mini
  obis_code: "31.7.0"
  name: "Current Phase 1"
  unit_of_measurement: A
  accuracy_decimals: 1
- platform: p1_mini
  obis_code: "51.7.0"
  name: "Current Phase 2"
  unit_of_measurement: A
  accuracy_decimals: 1
- platform: p1_mini
  obis_code: "71.7.0"
  name: "Current Phase 3"
  unit_of_measurement: A
  accuracy_decimals: 1
